#!/usr/bin/env bash

OPTIONS="Build-Dev\nBuild-Prod\nBash\nDown\nLogs"

# source configuration or use default values
if [ -f $HOME/.config/ouiscript/config ]; then
  source $HOME/.config/ouiscript/config
else
  LAUNCHER="rofi -width 30 -dmenu -i -p OuiCar-Script:"
fi

# Show exit wm option if exit command is provided as an argument
if [ ${#1} -gt 0 ]; then
  OPTIONS="Exit window manager\n$OPTIONS"
fi

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]
then
    case $option in
      Exit)
        eval $1
        ;;
      Build-Dev)
        i3-msg exec "kitty --hold --class=float_term docker exec frontend.node npm run build:dev"
        ;;
      Power-off)
        systemctl poweroff
        ;;
      Suspend)
        $($USE_LOCKER) && "$LOCKER"; systemctl suspend
        ;;
      Hibernate)
        $($USE_LOCKER) && "$LOCKER"; systemctl hibernate
        ;;
      *)
        ;;
    esac
fi
